# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish to vscode extension marketplace

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      VSCE_AIUTH_TOKEN: ${{secrets.RELEASE_TOEKN}}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: 'install dependencies'
        run: yarn
      - name: 'Publish to marketplace'
        run: 'yarn publish -p $VSCE_AIUTH_TOKEN'
        env:
          VSCE_AIUTH_TOKEN: ${{secrets.RELEASE_TOEKN}}
